/*Caso 4*/
CREATE TABLE HIST_REBAJA_ARRIENDO AS
SELECT
    extract(year from sysdate) "ANNO_PROCESO",
    nro_patente "NRO_PATENTE",
    valor_arriendo_dia "VALOR_ARRIENDO_DIA_SR",
    valor_garantia_dia "VALOR_GARANTIA_DIA_SR",
    extract(year from sysdate)-anio "ANNO_ANTIGUEDAD",
    valor_arriendo_dia-((extract(year from sysdate)-anio)/100 * valor_arriendo_dia) "VALOR_ARRIENDO_DS",
    valor_garantia_dia-((extract(year from sysdate)-anio)/100*valor_garantia_dia) "VALOR_GARANTIA_DS"
FROM CAMION WHERE extract(year from sysdate)-anio > 5
ORDER BY "ANNO_ANTIGUEDAD" DESC, nro_patente ASC;

/*FUNCIONES DE GRUPO Y AGRUPACION*/

SELECT
    COUNT(sueldo_base) "CONTAR" /*<-- NO CUENTAN LOS VALORES NULOS*/,
    SUM(SUELDO_BASE) "SUMAR" /*<-- SUAM TODOS LOS SUELDOS*/,
    ROUND(AVG(SUELDO_BASE)) "PROMEDIAR" /*PROMEDIA LOS SUELDOS*/,
    MAX(SUELDO_BASE) "MAXIMO" /*<-- VE EL EMPLEADO QUE GANA MAS*/,
    MIN(sueldo_base) "MINIMO" /*<-- VE EL EMPLEADO QUE GANA MENOS*/
FROM EMPLEADO;

/*GROUP BY <-- AGRUPAR CONSULTAS A PARTIR DE UN ATRIBUTO*/
SELECT
    SEXO "GENERO",
    COUNT(*) "CANTIDAD",
    ROUND(AVG(sueldo_base)) "PROMEDIO SALARIAL",
    MAX(sueldo_base) "SUELDO ALTO",
    MIN(sueldo_base) "SUELDO BAJO"
FROM EMPLEADO
GROUP BY SEXO; /*ORDENANDO POR EL VALOR PUEDO USAR UN DATO SINGULAR(SEXO) EN UNA CONSULTA CON AGRUPACION(COUNT)*/
/*CANTIDAD DE ARRIENDOS POR CAMION*/
SELECT
    NRO_PATENTE "CAMION",
    COUNT(*) "CANTIDAD ARRIENDOS"
FROM ARRIENDO_CAMION
GROUP BY NRO_PATENTE
ORDER BY "CANTIDAD ARRIENDOS" DESC;
/*CANTIDAD DE CLIENTES SEGUN TIPO DE CLIENTE*/
SELECT
    COUNT(*) "CANTIDAD CADA TIPO"
FROM CLIENTE
GROUP BY ID_TIPO_CLI ORDER BY 1;



